version: '2.1'

services:
  mongodb:
    image: mongo:3.4.13
    ports:
      - "27017"
    command: mongod
  bigchaindb:
    depends_on:
      - mongodb
      - tendermint
    build:
      context: .
      dockerfile: ./compose/Dockerfile
      args:
        branch: master
        backend: localmongodb
    environment:
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 46657
    ports:
      - "9984"
      - "9985"
      - "46658"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl http://bigchaindb:9984 && curl http://tendermint:46657/abci_query"]
      interval: 3s
      timeout: 5s
      retries: 3
    command: bigchaindb -l DEBUG start
  tendermint:
    image: tendermint/tendermint:0.12
    volumes:
      - ./compose/tendermint/tmdata/config.toml:/tendermint/config.toml
    entrypoint: ''
    ports:
      - "46656"
      - "46657"
    command: bash -c "tendermint init && tendermint node"
